name: "Web-Beest - SEO"
description: "SEO modules for modern Drupal" 
type: "SEO"
install:
  - favicons
  - gdpr
  - httpswww
  - image
  - metatag
  - pathauto
  - redirect
  - schema_metatag
  - webp
  - xmlsitemap
  - yoast_seo
config:
  import:
    favicons: '*'
    gdpr: '*'
    httpswww: '*'
    metatag: '*'
    pathauto: '*'
    redirect: '*'
    schema_metatag: '*'
    webp: '*'
    xmlsitemap: '*'
    yoast_seo: '*'
  strict: false

